"""
app/api/alerts.py

FastAPI router for the Opportunity Radar product.

Endpoints:
  GET  /alerts          — List active trade signals.
  POST /test-signal     — Manually inject an event to test the pipeline.
"""

from __future__ import annotations

import uuid

from fastapi import APIRouter, HTTPException, Query
from pydantic import BaseModel

from app.services.opportunity_radar.agents import RadarState, radar_graph
from app.services.opportunity_radar.models import Alert, Event, EventType, SignalStrength

router = APIRouter()


# ── Request / response schemas specific to this router ────────────────────────

class TestSignalRequest(BaseModel):
    """Payload for manually injecting a test event into the pipeline."""

    title: str
    url: str | None = None
    language: str = "en"
    event_type: EventType = EventType.OTHER


# ── Endpoints ─────────────────────────────────────────────────────────────────

@router.get(
    "/alerts",
    response_model=list[Alert],
    summary="List active trade signals",
    description=(
        "Returns a list of high-confidence trade alerts generated by the "
        "Opportunity Radar pipeline. Alerts are derived from verified events "
        "mapped through the Neo4j causal knowledge graph.\n\n"
        "Supports optional filtering by symbol and minimum signal strength."
    ),
)
async def list_alerts(
    symbol: str | None = Query(None, description="Filter by NSE ticker symbol"),
    min_strength: SignalStrength | None = Query(
        None, description="Minimum signal strength: low | medium | high"
    ),
    limit: int = Query(20, ge=1, le=100, description="Maximum number of alerts to return"),
) -> list[Alert]:
    """
    Fetch active alerts from the alert store.

    # TODO: Query PostgreSQL for persisted Alert records ordered by created_at DESC.
    # TODO: Apply symbol and min_strength filters in the SQL WHERE clause.
    # TODO: Optionally subscribe to the Redis 'alerts' channel for real-time updates
    #       using Server-Sent Events (SSE) or WebSockets.
    """
    # Stub — return an empty list until DB persistence is wired up
    return []


@router.post(
    "/test-signal",
    response_model=Alert | None,
    summary="Inject a test event into the Opportunity Radar pipeline",
    description=(
        "Manually submits an event payload to the full Opportunity Radar "
        "LangGraph pipeline (HyperLocalScout → VerificationAgent → CausalMapper) "
        "and returns the resulting Alert if the event passes verification.\n\n"
        "Useful for end-to-end testing without waiting for a live ingestion cycle."
    ),
)
async def test_signal(body: TestSignalRequest) -> Alert | None:
    """
    Run the Opportunity Radar pipeline on a manually supplied event.

    Returns the generated Alert, or null if the event did not pass the
    verification confidence threshold.

    # TODO: Persist the test alert to PostgreSQL with a 'test' flag so it
    #       can be filtered out of production alert feeds.
    """
    initial_state: RadarState = {
        "raw_payload": {
            "title": body.title,
            "url": body.url,
            "language": body.language,
        },
        "event": None,
        "verified": False,
        "confidence_score": 0.0,
        "alert": None,
    }

    final_state = await radar_graph.ainvoke(initial_state)
    return final_state.get("alert")
